services:

  tests-awk:
    build:
      context: ../../..
      dockerfile: build-packages/config/__tests__/Dockerfile.awk
    working_dir: /workspace/dev-tools/build-packages
    volumes:
      # Mount repo root at /workspace
      - ../../../..:/workspace:rw

    # command will be provided by `docker compose run`
