# Wazuh dashboard SPEC
# Copyright (C) 2021, Wazuh Inc.
#
# This program is a free software; you can redistribute it
# and/or modify it under the terms of the GNU General Public
# License (version 2) as published by the FSF - Free Software
# Foundation.
Summary:     Wazuh dashboard is a user interface and visualization tool for security-related data. Documentation can be found at https://documentation.wazuh.com/current/getting-started/components/wazuh-dashboard.html
Name:        wazuh-dashboard
Version:     %{_version}
Release:     %{_release}
License:     GPL
Group:       System Environment/Daemons
Source0:     %{name}-%{version}.tar.gz
URL:         https://www.wazuh.com/
buildroot:   %{_tmppath}/%{name}-%{version}-%{release}-wazuh-dashboard-%(%{__id_u} -n)
Vendor:      Wazuh, Inc <info@wazuh.com>
Packager:    Wazuh, Inc <info@wazuh.com>
Requires(pre):    /usr/sbin/groupadd /usr/sbin/useradd
AutoReqProv: no
Requires: libcap, openssl, diffutils, util-linux
ExclusiveOS: linux

# -----------------------------------------------------------------------------

%global USER %{name}
%global GROUP %{name}
%global CONFIG_DIR /etc/%{name}
%global PID_DIR /run/%{name}
%global INSTALL_DIR /usr/share/%{name}
%global DASHBOARD_FILE wazuh-dashboard.tar.gz
%define _source_payload w9.gzdio
%define _binary_payload w9.gzdio
# Disable creation of /usr/lib/.build-id/* links
%define _build_id_links none
# Optional: don’t fail the build if build-ids are missing
%undefine _missing_build_ids_terminate_build

# -----------------------------------------------------------------------------


%description
Wazuh dashboard is a user interface and visualization tool for security-related data. This Wazuh central component enables exploring, visualizing, and analyzing the stored security alerts generated by the Wazuh server. Wazuh dashboard enables inspecting the status and managing the configurations of the Wazuh cluster and agents as well as creating and managing users and roles. In addition, it allows testing the ruleset and making calls to the Wazuh API. Documentation can be found at https://documentation.wazuh.com/current/getting-started/components/wazuh-dashboard.html

# -----------------------------------------------------------------------------

%prep

cp /tmp/%{DASHBOARD_FILE} ./

groupadd %{GROUP}
useradd -g %{GROUP} %{USER}

# -----------------------------------------------------------------------------

%build

tar -xf %{DASHBOARD_FILE}
sed -i 's/OSD_NODE_OPTS_PREFIX/OSD_PATH_CONF="\/etc\/wazuh-dashboard" OSD_NODE_OPTS_PREFIX/g' "wazuh-dashboard-base/bin/opensearch-dashboards"
sed -i 's/OSD_USE_NODE_JS_FILE_PATH/OSD_PATH_CONF="\/etc\/wazuh-dashboard" OSD_USE_NODE_JS_FILE_PATH/g' "wazuh-dashboard-base/bin/opensearch-dashboards-keystore"


# -----------------------------------------------------------------------------

%install

mkdir -p %{buildroot}%{CONFIG_DIR}
mkdir -p %{buildroot}%{INSTALL_DIR}
mkdir -p %{buildroot}/usr/lib/systemd/system
mkdir -p %{buildroot}%{_initrddir}
mkdir -p %{buildroot}/etc/default

mv wazuh-dashboard-base/config/node.options %{buildroot}%{CONFIG_DIR}
mv wazuh-dashboard-base/config/opensearch_dashboards.yml %{buildroot}%{CONFIG_DIR}
cp wazuh-dashboard-base/VERSION.json %{buildroot}%{INSTALL_DIR}

mv wazuh-dashboard-base/* %{buildroot}%{INSTALL_DIR}

# Set custom welcome styles

mkdir -p %{buildroot}%{INSTALL_DIR}/config

cp %{buildroot}%{INSTALL_DIR}/etc/services/wazuh-dashboard.service %{buildroot}/usr/lib/systemd/system/wazuh-dashboard.service
cp %{buildroot}%{INSTALL_DIR}/etc/services/default %{buildroot}/etc/default/wazuh-dashboard

chmod 644 %{buildroot}/usr/lib/systemd/system/wazuh-dashboard.service
chmod 640 %{buildroot}/etc/default/wazuh-dashboard

rm -rf %{buildroot}%{INSTALL_DIR}/etc/

find %{buildroot}%{INSTALL_DIR} -exec chown %{USER}:%{GROUP} {} \;
find %{buildroot}%{CONFIG_DIR} -exec chown %{USER}:%{GROUP} {} \;

chown root:root %{buildroot}/usr/lib/systemd/system/wazuh-dashboard.service

find %{buildroot}%{INSTALL_DIR} -type f -exec chmod go+rX,go-w {} \;
find %{buildroot}%{INSTALL_DIR} -type d -exec chmod 755 {} \;

# -----------------------------------------------------------------------------

%pre
# Block installation of 5.x if any Wazuh < 5.0.0 is detected on disk.
# NOTE: we check files on disk rather than rpm -qa because during
# rpm -Uvh the old package header is removed from the DB before %pre runs.
# Detection order:
#   1. VERSION.json        — wazuh-dashboard 5.x+
#   2. VERSION             — wazuh-dashboard 4.x (legacy file)
#   3. plugin package.json — wazuh-dashboard 4.x+ (plugin metadata)
print_upgrade_error() {
    cat >&2 <<EOF
==============================================================
ERROR: Upgrade from Wazuh dashboard versions prior to 5.x is not supported.

Detected installed version: ${1:-undetermined}

A clean installation of Wazuh dashboard 5.x is required.
Refer to the 5.x migration guide for more information.
==============================================================
EOF
}

if [ -f %{INSTALL_DIR}/VERSION.json ]; then
  INSTALLED_VER=$(grep -m 1 '"version"' %{INSTALL_DIR}/VERSION.json 2>/dev/null | sed 's/.*"version": *"\([^"]*\)".*/\1/')
elif [ -f %{INSTALL_DIR}/VERSION ]; then
  INSTALLED_VER=$(cat %{INSTALL_DIR}/VERSION 2>/dev/null)
elif [ -f %{INSTALL_DIR}/plugins/wazuh/package.json ]; then
  INSTALLED_VER=$(grep -m 1 '"version"' %{INSTALL_DIR}/plugins/wazuh/package.json 2>/dev/null | sed 's/.*"version": *"\([^"]*\)".*/\1/')
fi

if [ -n "$INSTALLED_VER" ]; then
  MAJOR=$(echo "$INSTALLED_VER" | cut -d. -f1)
  if [ "$MAJOR" -lt 5 ]; then
    print_upgrade_error "$INSTALLED_VER"
    exit 1
  fi
elif [ "$1" = "2" ] && [ -d %{INSTALL_DIR}/plugins ]; then
  # Upgrade requested but version could not be determined from any source.
  # Files may have been removed or corrupted. Block the upgrade; a fresh
  # install ($1=1) is still allowed.
  print_upgrade_error
  exit 1
fi

# Create the wazuh-dashboard group if it doesn't exists
if [ $1 = 1 ]; then
  if command -v getent > /dev/null 2>&1 && ! getent group %{GROUP} > /dev/null 2>&1; then
    groupadd -r %{GROUP}
  elif ! getent group %{GROUP} > /dev/null 2>&1; then
    groupadd -r %{GROUP}
  fi
  # Create the wazuh-dashboard user if it doesn't exists
  if ! getent passwd %{USER} > /dev/null 2>&1; then
    useradd -g %{GROUP} -G %{USER} -d %{INSTALL_DIR}/ -r -s /sbin/nologin wazuh-dashboard
  fi
fi
# Stop the services to upgrade the package
if [ $1 = 2 ]; then
  if command -v systemctl > /dev/null 2>&1 && systemctl > /dev/null 2>&1 && systemctl is-active --quiet wazuh-dashboard > /dev/null 2>&1; then
    systemctl stop wazuh-dashboard.service > /dev/null 2>&1
    touch %{INSTALL_DIR}/wazuh-dashboard.restart
  # Check for SysV
  elif command -v service > /dev/null 2>&1 && service wazuh-dashboard status 2>/dev/null | grep "is running" > /dev/null 2>&1; then
    service wazuh-dashboard stop > /dev/null 2>&1
    touch %{INSTALL_DIR}/wazuh-dashboard.restart
  fi
fi

# -----------------------------------------------------------------------------

%post
setcap 'cap_net_bind_service=+ep' %{INSTALL_DIR}/node/bin/node
rm -f /usr/share/wazuh-dashboard/VERSION
# Root reads the environment file at every start, so the service user must not own it
if [ -f /etc/default/wazuh-dashboard ]; then
  chown root:%{GROUP} /etc/default/wazuh-dashboard
  chmod 640 /etc/default/wazuh-dashboard
fi

# A certificate pair staged before the package was installed -- by the
# installation assistant, or by an operator -- is root's: the service user did
# not exist yet. The resolver keeps an existing pair exactly as it finds it, and
# the service reads it after dropping privileges, so it must be the service
# user's. DEB does the same for the whole configuration directory in its
# postinst; the indexer and the manager do it in their packaging too. On an
# upgrade this also repairs a host that was left unable to start. -P never
# follows a symlink, and a certs/ that is itself one is left alone.
if [ -d %{CONFIG_DIR}/certs ] && [ ! -L %{CONFIG_DIR}/certs ]; then
  chown -R -P %{USER}:%{GROUP} %{CONFIG_DIR}/certs || true
fi
# Removing the package hands what it kept in the configuration directory over to
# root before the service user goes, so a fresh install takes all of it back.
if [ $1 = 1 ] && [ -d %{CONFIG_DIR} ] && [ ! -L %{CONFIG_DIR} ]; then
  chown -R -P %{USER}:%{GROUP} %{CONFIG_DIR} || true
fi

# Create the keystore if needed, resolve the consumed kibanaserver and
# wazuh-wui passwords into it and, on a fresh install, generate the AI
# assistant encryption key. An unresolved credential is not an error at
# install time: the unit's pre-start step runs the resolver again and
# refuses to start if needed.
# $1 is 1 on a fresh install and 2 or more on an upgrade.
if [ $1 = 1 ]; then
  %{INSTALL_DIR}/bin/resolve-credentials --install || true
else
  %{INSTALL_DIR}/bin/resolve-credentials --upgrade || true
fi
# The keystore holds secrets under an empty password, so its mode must keep it private
# on fresh installs and on upgrades of keystores created with a wider mode
if [ -f %{CONFIG_DIR}/opensearch_dashboards.keystore ]; then
  chown %{USER}:%{GROUP} %{CONFIG_DIR}/opensearch_dashboards.keystore
  chmod 600 %{CONFIG_DIR}/opensearch_dashboards.keystore
fi

# -----------------------------------------------------------------------------

%preun
if [ $1 = 0 ];then # Remove
  echo -n "Stopping wazuh-dashboard service..."
  if command -v systemctl > /dev/null 2>&1 && systemctl > /dev/null 2>&1; then
      systemctl --no-reload stop wazuh-dashboard.service > /dev/null 2>&1
      systemctl --no-reload disable wazuh-dashboard.service > /dev/null 2>&1 || true
  # Check for SysV
  elif command -v service > /dev/null 2>&1; then
    service wazuh-dashboard stop > /dev/null 2>&1
  fi
fi

# -----------------------------------------------------------------------------

%postun
if [ $1 = 0 ];then
  # If the package is been uninstalled
  # rpm keeps the configuration directory: the certificates and their private
  # keys, the keystore and any *.rpmsave. Hand every file the service account
  # owns there over to root, with group and other access stripped, before the
  # account goes. userdel frees the UID, and the next system account created
  # would inherit it -- and with it the secrets left behind. Nothing is deleted:
  # %post takes the directory back on a reinstall. find -P and chown -h act on
  # links themselves and chmod never sees one, so a link the account planted
  # cannot aim any of this at another file. Same as the Wazuh indexer package.
  if getent passwd %{USER} > /dev/null 2>&1 && [ -d %{CONFIG_DIR} ] && [ ! -L %{CONFIG_DIR} ]; then
    config_dir_ok=true
    find -P %{CONFIG_DIR} -user %{USER} \
      \( -type l -o -exec chmod go-rwx {} + \) \
      -exec chown -h root:root {} + 2>/dev/null || config_dir_ok=false
    find -P %{CONFIG_DIR} -group %{GROUP} \
      \( -type l -o -exec chmod g-rwx {} + \) \
      -exec chgrp -h root {} + 2>/dev/null || config_dir_ok=false
    if [ "${config_dir_ok}" = true ]; then
      echo "Kept %{CONFIG_DIR}, now owned by root. Reinstalling %{name} takes it back."
    else
      echo "Some files under %{CONFIG_DIR} could not be handed over to root; they keep the ID of the removed %{name} user." >&2
    fi
  fi
  # A modified environment file is kept as .rpmsave with its root:%{GROUP}
  # ownership. The group goes too, so it becomes root's as well.
  if [ -f /etc/default/%{name}.rpmsave ] && [ ! -L /etc/default/%{name}.rpmsave ]; then
    chgrp root /etc/default/%{name}.rpmsave > /dev/null 2>&1 || true
    chmod g-rwx /etc/default/%{name}.rpmsave > /dev/null 2>&1 || true
  fi

  # Remove the wazuh-dashboard user if it exists
  if getent passwd %{USER} > /dev/null 2>&1; then
    userdel %{USER} >/dev/null 2>&1
  fi
  # Remove the wazuh-dashboard group if it exists
  if command -v getent > /dev/null 2>&1 && getent group %{GROUP} > /dev/null 2>&1; then
    groupdel %{GROUP} >/dev/null 2>&1
  elif getent group %{GROUP} > /dev/null 2>&1; then
    groupdel %{GROUP} >/dev/null 2>&1
  fi

  # Remove /etc/wazuh-dashboard and /usr/share/wazuh-dashboard dirs
  rm -rf %{INSTALL_DIR}
  if [ -d %{PID_DIR} ]; then
    rm -rf %{PID_DIR}
  fi

  # The dashboard owns no key in /etc/wazuh/credentials.env. The shared
  # /etc/wazuh directory (credentials file and default CA directory) is only
  # removed by the last Wazuh central component to leave the host.
  if ! rpm -q --quiet wazuh-indexer && ! rpm -q --quiet wazuh-manager; then
    rm -rf /etc/wazuh
  fi

  # Make systemd forget the unit, now that its file is gone
  if command -v systemctl > /dev/null 2>&1 && systemctl > /dev/null 2>&1; then
    systemctl daemon-reload > /dev/null 2>&1 || true
  fi
fi

# -----------------------------------------------------------------------------

# posttrans code is the last thing executed in a install/upgrade
%posttrans
if [ ! -d %{PID_DIR} ]; then
    mkdir -p %{PID_DIR}
    chown %{USER}:%{GROUP} %{PID_DIR}
fi

if [ -f %{INSTALL_DIR}/wazuh-dashboard.restart ]; then
  rm -f %{INSTALL_DIR}/wazuh-dashboard.restart
  if command -v systemctl > /dev/null 2>&1 && systemctl > /dev/null 2>&1; then
    systemctl restart wazuh-dashboard.service > /dev/null 2>&1
  # Check for SysV
  elif command -v service > /dev/null 2>&1; then
    service wazuh-dashboard restart > /dev/null 2>&1
  fi

fi


# -----------------------------------------------------------------------------

%clean
rm -fr %{buildroot}

# -----------------------------------------------------------------------------

%files
%defattr(-,%{USER},%{GROUP})
%dir %attr(750, %{USER}, %{GROUP}) %{CONFIG_DIR}

%config(noreplace) %attr(0640, root, %{GROUP}) "/etc/default/wazuh-dashboard"
%config(noreplace) %attr(0640, %{USER}, %{GROUP}) "%{CONFIG_DIR}/opensearch_dashboards.yml"

%attr(444, root, root) %{INSTALL_DIR}/VERSION.json
%dir %attr(755, root, root) %{INSTALL_DIR}
%dir %attr(755, root, root) "%{INSTALL_DIR}/src"
%dir %attr(755, root, root) "%{INSTALL_DIR}/src/core"
%attr(-, root, root) "%{INSTALL_DIR}/src/core/*"
%dir %attr(755, root, root) "%{INSTALL_DIR}/src/cli_plugin"
%dir %attr(755, root, root) "%{INSTALL_DIR}/src/cli_plugin/remove"
%dir %attr(755, root, root) "%{INSTALL_DIR}/src/cli_plugin/list"
%dir %attr(755, root, root) "%{INSTALL_DIR}/src/cli_plugin/lib"
%dir %attr(755, root, root) "%{INSTALL_DIR}/src/cli_plugin/install"
%dir %attr(755, root, root) "%{INSTALL_DIR}/src/cli_plugin/install/downloaders"
%dir %attr(755, root, root) "%{INSTALL_DIR}/src/cli_plugin/install/__fixtures__"
%dir %attr(755, root, root) "%{INSTALL_DIR}/src/cli_plugin/install/__fixtures__/replies"
%dir %attr(755, root, root) "%{INSTALL_DIR}/src/cli_keystore"
%dir %attr(755, root, root) "%{INSTALL_DIR}/src/cli_keystore/utils"
%dir %attr(755, root, root) "%{INSTALL_DIR}/src/setup_node_env"
%dir %attr(755, root, root) "%{INSTALL_DIR}/src/setup_node_env/root"
%dir %attr(755, root, root) "%{INSTALL_DIR}/src/setup_node_env/harden"
%dir %attr(755, root, root) "%{INSTALL_DIR}/src/optimize"
%dir %attr(755, root, root) "%{INSTALL_DIR}/src/optimize/bundles_route"
%dir %attr(755, root, root) "%{INSTALL_DIR}/src/optimize/bundles_route/__fixtures__"
%dir %attr(755, root, root) "%{INSTALL_DIR}/src/optimize/bundles_route/__fixtures__/plugin"
%dir %attr(755, root, root) "%{INSTALL_DIR}/src/optimize/bundles_route/__fixtures__/plugin/foo"
%dir %attr(755, root, root) "%{INSTALL_DIR}/src/plugins"
%attr(-, root, root) "%{INSTALL_DIR}/src/plugins/*
%dir %attr(755, root, root) "%{INSTALL_DIR}/src/cli"
%dir %attr(755, root, root) "%{INSTALL_DIR}/src/cli/serve"
%dir %attr(755, root, root) "%{INSTALL_DIR}/src/cli/serve/integration_tests"
%dir %attr(755, root, root) "%{INSTALL_DIR}/src/cli/serve/integration_tests/__fixtures__"
%dir %attr(755, root, root) "%{INSTALL_DIR}/src/cli/serve/integration_tests/__fixtures__/reload_logging_config"
%dir %attr(755, root, root) "%{INSTALL_DIR}/src/legacy"
%dir %attr(755, root, root) "%{INSTALL_DIR}/src/legacy/utils"
%dir %attr(755, root, root) "%{INSTALL_DIR}/src/legacy/server"
%dir %attr(755, root, root) "%{INSTALL_DIR}/src/legacy/server/logging"
%dir %attr(755, root, root) "%{INSTALL_DIR}/src/legacy/server/logging/rotate"
%dir %attr(755, root, root) "%{INSTALL_DIR}/src/legacy/server/core"
%dir %attr(755, root, root) "%{INSTALL_DIR}/src/legacy/server/i18n"
%dir %attr(755, root, root) "%{INSTALL_DIR}/src/legacy/server/i18n/localization"
%dir %attr(755, root, root) "%{INSTALL_DIR}/src/legacy/server/warnings"
%dir %attr(755, root, root) "%{INSTALL_DIR}/src/legacy/server/http"
%dir %attr(755, root, root) "%{INSTALL_DIR}/src/legacy/server/config"
%dir %attr(755, root, root) "%{INSTALL_DIR}/src/legacy/server/keystore"
%dir %attr(755, root, root) "%{INSTALL_DIR}/src/legacy/ui"
%dir %attr(755, root, root) "%{INSTALL_DIR}/src/legacy/ui/ui_render"
%dir %attr(755, root, root) "%{INSTALL_DIR}/src/legacy/ui/ui_render/bootstrap"
%dir %attr(755, root, root) "%{INSTALL_DIR}/src/legacy/ui/apm"
%dir %attr(755, root, root) "%{INSTALL_DIR}/src/docs"
%dir %attr(755, root, root) "%{INSTALL_DIR}/src/translations"
%dir %attr(755, root, root) "%{INSTALL_DIR}/node_modules"
%attr(-, root, root) "%{INSTALL_DIR}/node_modules/*"
%attr(644, root, root) "%{INSTALL_DIR}/node_modules/.yarn-integrity"
%dir %attr(755, root, root) "%{INSTALL_DIR}/node"
%attr(-, root, root) "%{INSTALL_DIR}/node/*"
%dir %attr(750, %{USER}, %{GROUP}) "%{INSTALL_DIR}/data"
%dir %attr(755, root, root) "%{INSTALL_DIR}/plugins"
%attr(-, root, root) "%{INSTALL_DIR}/plugins/*"
%dir %attr(755, root, root) "%{INSTALL_DIR}/bin"
%attr(644, root, root) "%{INSTALL_DIR}/src/cli_plugin/remove/settings.js"
%attr(644, root, root) "%{INSTALL_DIR}/src/cli_plugin/remove/index.js"
%attr(644, root, root) "%{INSTALL_DIR}/src/cli_plugin/remove/remove.js"
%attr(644, root, root) "%{INSTALL_DIR}/src/cli_plugin/dev.js"
%attr(644, root, root) "%{INSTALL_DIR}/src/cli_plugin/list/index.js"
%attr(644, root, root) "%{INSTALL_DIR}/src/cli_plugin/list/list.js"
%attr(644, root, root) "%{INSTALL_DIR}/src/cli_plugin/lib/logger.js"
%attr(644, root, root) "%{INSTALL_DIR}/src/cli_plugin/lib/errors.js"
%attr(644, root, root) "%{INSTALL_DIR}/src/cli_plugin/lib/log_warnings.js"
%attr(644, root, root) "%{INSTALL_DIR}/src/cli_plugin/install/opensearch_dashboards.js"
%attr(644, root, root) "%{INSTALL_DIR}/src/cli_plugin/install/downloaders/file.js"
%attr(644, root, root) "%{INSTALL_DIR}/src/cli_plugin/install/downloaders/http.js"
%attr(644, root, root) "%{INSTALL_DIR}/src/cli_plugin/install/zip.js"
%attr(644, root, root) "%{INSTALL_DIR}/src/cli_plugin/install/download.js"
%attr(644, root, root) "%{INSTALL_DIR}/src/cli_plugin/install/install.js"
%attr(644, root, root) "%{INSTALL_DIR}/src/cli_plugin/install/settings.js"
%attr(644, root, root) "%{INSTALL_DIR}/src/cli_plugin/install/rename.js"
%attr(644, root, root) "%{INSTALL_DIR}/src/cli_plugin/install/index.js"
%attr(644, root, root) "%{INSTALL_DIR}/src/cli_plugin/install/__fixtures__/replies/invalid_name.zip"
%attr(644, root, root) "%{INSTALL_DIR}/src/cli_plugin/install/__fixtures__/replies/test_plugin_different_version.zip"
%attr(644, root, root) "%{INSTALL_DIR}/src/cli_plugin/install/__fixtures__/replies/banana.jpg"
%attr(644, root, root) "%{INSTALL_DIR}/src/cli_plugin/install/__fixtures__/replies/test_plugin_no_opensearch_dashboards.zip"
%attr(644, root, root) "%{INSTALL_DIR}/src/cli_plugin/install/__fixtures__/replies/test_plugin.zip"
%attr(644, root, root) "%{INSTALL_DIR}/src/cli_plugin/install/__fixtures__/replies/corrupt.zip"
%attr(644, root, root) "%{INSTALL_DIR}/src/cli_plugin/install/__fixtures__/replies/test_plugin_many.zip"
%attr(644, root, root) "%{INSTALL_DIR}/src/cli_plugin/install/cleanup.js"
%attr(644, root, root) "%{INSTALL_DIR}/src/cli_plugin/install/pack.js"
%attr(644, root, root) "%{INSTALL_DIR}/src/cli_plugin/install/progress.js"
%attr(644, root, root) "%{INSTALL_DIR}/src/cli_plugin/cli.js"
%attr(644, root, root) "%{INSTALL_DIR}/src/cli_plugin/dist.js"
%attr(644, root, root) "%{INSTALL_DIR}/src/cli_keystore/cli_keystore.js"
%attr(644, root, root) "%{INSTALL_DIR}/src/cli_keystore/add.js"
%attr(644, root, root) "%{INSTALL_DIR}/src/cli_keystore/create.js"
%attr(644, root, root) "%{INSTALL_DIR}/src/cli_keystore/utils/index.js"
%attr(644, root, root) "%{INSTALL_DIR}/src/cli_keystore/utils/prompt.js"
%attr(644, root, root) "%{INSTALL_DIR}/src/cli_keystore/dev.js"
%attr(644, root, root) "%{INSTALL_DIR}/src/cli_keystore/get_keystore.js"
%attr(644, root, root) "%{INSTALL_DIR}/src/cli_keystore/remove.js"
%attr(644, root, root) "%{INSTALL_DIR}/src/cli_keystore/dist.js"
%attr(644, root, root) "%{INSTALL_DIR}/src/cli_keystore/list.js"
%attr(644, root, root) "%{INSTALL_DIR}/src/apm.js"
%attr(644, root, root) "%{INSTALL_DIR}/src/setup_node_env/root/force.js"
%attr(644, root, root) "%{INSTALL_DIR}/src/setup_node_env/root/is_root.js"
%attr(644, root, root) "%{INSTALL_DIR}/src/setup_node_env/root/index.js"
%attr(644, root, root) "%{INSTALL_DIR}/src/setup_node_env/polyfill.js"
%attr(644, root, root) "%{INSTALL_DIR}/src/setup_node_env/node_version_validator.js"
%attr(644, root, root) "%{INSTALL_DIR}/src/setup_node_env/index.js"
%attr(644, root, root) "%{INSTALL_DIR}/src/setup_node_env/harden/index.js"
%attr(644, root, root) "%{INSTALL_DIR}/src/setup_node_env/harden/child_process.js"
%attr(644, root, root) "%{INSTALL_DIR}/src/setup_node_env/no_transpilation.js"
%attr(644, root, root) "%{INSTALL_DIR}/src/setup_node_env/exit_on_warning.js"
%attr(644, root, root) "%{INSTALL_DIR}/src/setup_node_env/dist.js"
%attr(644, root, root) "%{INSTALL_DIR}/src/optimize/np_ui_plugin_public_dirs.js"
%attr(644, root, root) "%{INSTALL_DIR}/src/optimize/index.js"
%attr(644, root, root) "%{INSTALL_DIR}/src/optimize/optimize_mixin.js"
%attr(644, root, root) "%{INSTALL_DIR}/src/optimize/bundles_route/proxy_bundles_route.js"
%attr(644, root, root) "%{INSTALL_DIR}/src/optimize/bundles_route/file_hash.js"
%attr(644, root, root) "%{INSTALL_DIR}/src/optimize/bundles_route/file_hash_cache.js"
%attr(644, root, root) "%{INSTALL_DIR}/src/optimize/bundles_route/index.js"
%attr(644, root, root) "%{INSTALL_DIR}/src/optimize/bundles_route/__fixtures__/plugin/foo/plugin.js"
%attr(644, root, root) "%{INSTALL_DIR}/src/optimize/bundles_route/__fixtures__/outside_output.js"
%attr(644, root, root) "%{INSTALL_DIR}/src/optimize/bundles_route/bundles_route.js"
%attr(644, root, root) "%{INSTALL_DIR}/src/optimize/bundles_route/dynamic_asset_response.js"
%attr(644, root, root) "%{INSTALL_DIR}/src/cli/command.js"
%attr(644, root, root) "%{INSTALL_DIR}/src/cli/help.js"
%attr(644, root, root) "%{INSTALL_DIR}/src/cli/cli.js"
%attr(644, root, root) "%{INSTALL_DIR}/src/cli/serve/serve.js"
%attr(644, root, root) "%{INSTALL_DIR}/src/cli/serve/read_keystore.js"
%attr(644, root, root) "%{INSTALL_DIR}/src/cli/serve/integration_tests/__fixtures__/invalid_config.yml"
%attr(644, root, root) "%{INSTALL_DIR}/src/cli/serve/integration_tests/__fixtures__/reload_logging_config/opensearch_dashboards_log_file.test.yml"
%attr(644, root, root) "%{INSTALL_DIR}/src/cli/serve/integration_tests/__fixtures__/reload_logging_config/opensearch_dashboards_log_console.test.yml"
%attr(644, root, root) "%{INSTALL_DIR}/src/cli/serve/integration_tests/__fixtures__/reload_logging_config/opensearch_dashboards.test.yml"
%attr(644, root, root) "%{INSTALL_DIR}/src/cli/dist.js"
%attr(644, root, root) "%{INSTALL_DIR}/src/legacy/utils/index.js"
%attr(644, root, root) "%{INSTALL_DIR}/src/legacy/utils/unset.js"
%attr(644, root, root) "%{INSTALL_DIR}/src/legacy/utils/version.js"
%attr(644, root, root) "%{INSTALL_DIR}/src/legacy/utils/artifact_type.js"
%attr(644, root, root) "%{INSTALL_DIR}/src/legacy/utils/deep_clone_with_buffers.js"
%attr(644, root, root) "%{INSTALL_DIR}/src/legacy/server/logging/rotate/index.js"
%attr(644, root, root) "%{INSTALL_DIR}/src/legacy/server/logging/rotate/log_rotator.js"
%attr(644, root, root) "%{INSTALL_DIR}/src/legacy/server/logging/apply_filters_to_keys.js"
%attr(644, root, root) "%{INSTALL_DIR}/src/legacy/server/logging/log_format.js"
%attr(644, root, root) "%{INSTALL_DIR}/src/legacy/server/logging/log_reporter.js"
%attr(644, root, root) "%{INSTALL_DIR}/src/legacy/server/logging/log_format_json.js"
%attr(644, root, root) "%{INSTALL_DIR}/src/legacy/server/logging/log_with_metadata.js"
%attr(644, root, root) "%{INSTALL_DIR}/src/legacy/server/logging/index.js"
%attr(644, root, root) "%{INSTALL_DIR}/src/legacy/server/logging/configuration.js"
%attr(644, root, root) "%{INSTALL_DIR}/src/legacy/server/logging/log_interceptor.js"
%attr(644, root, root) "%{INSTALL_DIR}/src/legacy/server/logging/log_format_string.js"
%attr(644, root, root) "%{INSTALL_DIR}/src/legacy/server/core/index.js"
%attr(644, root, root) "%{INSTALL_DIR}/src/legacy/server/i18n/localization/index.js"
%attr(644, root, root) "%{INSTALL_DIR}/src/legacy/server/i18n/localization/telemetry_localization_collector.js"
%attr(644, root, root) "%{INSTALL_DIR}/src/legacy/server/i18n/localization/file_integrity.js"
%attr(644, root, root) "%{INSTALL_DIR}/src/legacy/server/i18n/index.js"
%attr(644, root, root) "%{INSTALL_DIR}/src/legacy/server/i18n/get_translations_path.js"
%attr(644, root, root) "%{INSTALL_DIR}/src/legacy/server/i18n/constants.js"
%attr(644, root, root) "%{INSTALL_DIR}/src/legacy/server/osd_server.js"
%attr(644, root, root) "%{INSTALL_DIR}/src/legacy/server/warnings/index.js"
%attr(644, root, root) "%{INSTALL_DIR}/src/legacy/server/http/index.js"
%attr(644, root, root) "%{INSTALL_DIR}/src/legacy/server/http/register_hapi_plugins.js"
%attr(644, root, root) "%{INSTALL_DIR}/src/legacy/server/http/setup_base_path_provider.js"
%attr(644, root, root) "%{INSTALL_DIR}/src/legacy/server/config/override.js"
%attr(644, root, root) "%{INSTALL_DIR}/src/legacy/server/config/complete.js"
%attr(644, root, root) "%{INSTALL_DIR}/src/legacy/server/config/index.js"
%attr(644, root, root) "%{INSTALL_DIR}/src/legacy/server/config/schema.js"
%attr(644, root, root) "%{INSTALL_DIR}/src/legacy/server/config/config.js"
%attr(644, root, root) "%{INSTALL_DIR}/src/legacy/server/keystore/keystore.js"
%attr(644, root, root) "%{INSTALL_DIR}/src/legacy/server/keystore/index.js"
%attr(644, root, root) "%{INSTALL_DIR}/src/legacy/server/keystore/errors.js"
%attr(644, root, root) "%{INSTALL_DIR}/src/legacy/ui/ui_mixin.js"
%attr(644, root, root) "%{INSTALL_DIR}/src/legacy/ui/ui_render/ui_render_mixin.js"
%attr(644, root, root) "%{INSTALL_DIR}/src/legacy/ui/ui_render/utils.js"
%attr(644, root, root) "%{INSTALL_DIR}/src/legacy/ui/ui_render/index.js"
%attr(644, root, root) "%{INSTALL_DIR}/src/legacy/ui/ui_render/bootstrap/osd_bundles_loader_source.js"
%attr(644, root, root) "%{INSTALL_DIR}/src/legacy/ui/ui_render/bootstrap/index.js"
%attr(644, root, root) "%{INSTALL_DIR}/src/legacy/ui/ui_render/bootstrap/startup.js.hbs"
%attr(644, root, root) "%{INSTALL_DIR}/src/legacy/ui/ui_render/bootstrap/bootstrap.js.hbs"
%attr(644, root, root) "%{INSTALL_DIR}/src/legacy/ui/ui_render/bootstrap/app_bootstrap.js"
%attr(644, root, root) "%{INSTALL_DIR}/src/legacy/ui/index.js"
%attr(644, root, root) "%{INSTALL_DIR}/src/legacy/ui/apm/index.js"
%attr(644, root, root) "%{INSTALL_DIR}/src/docs/docs_repo.js"
%attr(644, root, root) "%{INSTALL_DIR}/src/docs/cli.js"
%attr(644, root, root) "%{INSTALL_DIR}/src/translations/de-DE.json"
%attr(644, root, root) "%{INSTALL_DIR}/src/translations/es-419.json"
%attr(644, root, root) "%{INSTALL_DIR}/src/translations/es-ES.json"
%attr(644, root, root) "%{INSTALL_DIR}/src/translations/fr-CA.json"
%attr(644, root, root) "%{INSTALL_DIR}/src/translations/fr-FR.json"
%attr(644, root, root) "%{INSTALL_DIR}/src/translations/id-ID.json"
%attr(644, root, root) "%{INSTALL_DIR}/src/translations/it-IT.json"
%attr(644, root, root) "%{INSTALL_DIR}/src/translations/ja-JP.json"
%attr(644, root, root) "%{INSTALL_DIR}/src/translations/ko-KR.json"
%attr(644, root, root) "%{INSTALL_DIR}/src/translations/pt-PT.json"
%attr(644, root, root) "%{INSTALL_DIR}/src/translations/tr-TR.json"
%attr(644, root, root) "%{INSTALL_DIR}/src/translations/zh-CN.json"
%attr(644, root, root) "%{INSTALL_DIR}/src/translations/zh-TW.json"
%attr(644, root, root) "%{INSTALL_DIR}/src/translations/pt-BR.json"
%attr(644, root, root) "%{INSTALL_DIR}/package.json"
%attr(644, root, root) "%{INSTALL_DIR}/LICENSE.txt"
%attr(644, root, root) "%{INSTALL_DIR}/NOTICE.txt"
%attr(644, root, root) "%{INSTALL_DIR}/README.txt"
%attr(755, root, root) "%{INSTALL_DIR}/bin/use_node"
%attr(755, root, root) "%{INSTALL_DIR}/bin/opensearch-dashboards"
%attr(755, root, root) "%{INSTALL_DIR}/bin/opensearch-dashboards-plugin"
%attr(755, root, root) "%{INSTALL_DIR}/bin/opensearch-dashboards-keystore"
%attr(750, root, root) "%{INSTALL_DIR}/bin/resolve-credentials"
%dir %attr(755, root, root) "%{INSTALL_DIR}/lib"
%attr(644, root, root) "%{INSTALL_DIR}/lib/wazuh-credentials.sh"
%dir %attr(755, root, root) "%{INSTALL_DIR}/config"
%attr(640, %{USER}, %{GROUP}) "%{CONFIG_DIR}/node.options"
%attr(644, root, root) "/usr/lib/systemd/system/wazuh-dashboard.service"

%changelog
* Wed Oct 14 2026 support <info@wazuh.com> - 5.0.0
- More info: https://documentation.wazuh.com/current/release-notes/release-5-0-0.html
* Thu Oct 08 2026 support <info@wazuh.com> - 4.14.10
- More info: https://documentation.wazuh.com/current/release-notes/release-4-14-10.html
* Wed Oct 07 2026 support <info@wazuh.com> - 4.14.9
- More info: https://documentation.wazuh.com/current/release-notes/release-4-14-9.html
* Wed Sep 23 2026 support <info@wazuh.com> - 4.14.8
- More info: https://documentation.wazuh.com/current/release-notes/release-4-14-8.html
* Thu Sep 03 2026 support <info@wazuh.com> - 4.10.5
- More info: https://documentation.wazuh.com/current/release-notes/release-4-10-5.html
* Wed Jul 29 2026 support <info@wazuh.com> - 4.14.7
- More info: https://documentation.wazuh.com/current/release-notes/release-4-14-7.html
* Wed Jul 01 2026 support <info@wazuh.com> - 4.14.6
- More info: https://documentation.wazuh.com/current/release-notes/release-4-14-6.html
* Thu May 21 2026 support <info@wazuh.com> - 4.10.4
- More info: https://documentation.wazuh.com/current/release-notes/release-4-10-4.html
* Thu Apr 23 2026 support <info@wazuh.com> - 4.14.5
- More info: https://documentation.wazuh.com/current/release-notes/release-4-14-5.html
* Tue Mar 17 2026 support <info@wazuh.com> - 4.14.4
- More info: https://documentation.wazuh.com/current/release-notes/release-4-14-4.html
* Wed Feb 11 2026 support <info@wazuh.com> - 4.14.3
- More info: https://documentation.wazuh.com/current/release-notes/release-4-14-3.html
* Wed Jan 14 2026 support <info@wazuh.com> - 4.14.2
- More info: https://documentation.wazuh.com/current/release-notes/release-4-14-2.html
* Wed Nov 12 2025 support <info@wazuh.com> - 4.14.1
- More info: https://documentation.wazuh.com/current/release-notes/release-4-14-1.html
* Wed Oct 22 2025 support <info@wazuh.com> - 4.14.0
- More info: https://documentation.wazuh.com/current/release-notes/release-4-14-0.html
* Wed Sep 24 2025 support <info@wazuh.com> - 4.13.1
- More info: https://documentation.wazuh.com/current/release-notes/release-4-13-1.html
* Thu Sep 18 2025 support <info@wazuh.com> - 4.13.0
- More info: https://documentation.wazuh.com/current/release-notes/release-4-13-0.html
* Fri Aug 22 2025 support <info@wazuh.com> - 4.10.3
- More info: https://documentation.wazuh.com/current/release-notes/release-4-10-3.html
* Wed May 21 2025 support <info@wazuh.com> - 4.10.2
- More info: https://documentation.wazuh.com/current/release-notes/release-4-10-2.html
* Wed May 07 2025 support <info@wazuh.com> - 4.12.0
- More info: https://documentation.wazuh.com/current/release-notes/release-4-12-0.html
* Tue Apr 01 2025 support <info@wazuh.com> - 4.11.2
- More info: https://documentation.wazuh.com/current/release-notes/release-4-11-2.html
* Wed Mar 12 2025 support <info@wazuh.com> - 4.11.1
- More info: https://documentation.wazuh.com/current/release-notes/release-4-11-1.html
* Fri Feb 21 2025 support <info@wazuh.com> - 4.11.0
- More info: https://documentation.wazuh.com/current/release-notes/release-4-11-0.html
* Thu Jan 16 2025 support <info@wazuh.com> - 4.10.1
- More info: https://documentation.wazuh.com/current/release-notes/release-4-10-1.html
* Wed Jan 08 2025 support <info@wazuh.com> - 4.10.0
- More info: https://documentation.wazuh.com/current/release-notes/release-4-10-0.html
* Mon Nov 04 2024 support <info@wazuh.com> - 4.9.2
- More info: https://documentation.wazuh.com/current/release-notes/release-4-9-2.html
* Tue Oct 15 2024 support <info@wazuh.com> - 4.9.1
- More info: https://documentation.wazuh.com/current/release-notes/release-4-9-1.html
* Thu Aug 15 2024 support <info@wazuh.com> - 4.9.0
- More info: https://documentation.wazuh.com/current/release-notes/release-4-9-0.html
* Tue Jan 30 2024 support <info@wazuh.com> - 4.8.1
- More info: https://documentation.wazuh.com/current/release-notes/release-4-8-1.html
* Fri Dec 15 2023 support <info@wazuh.com> - 4.8.0
- More info: https://documentation.wazuh.com/current/release-notes/release-4-8-0.html
* Tue Dec 05 2023 support <info@wazuh.com> - 4.7.1
- More info: https://documentation.wazuh.com/current/release-notes/release-4-7-1.html
* Tue Nov 21 2023 support <info@wazuh.com> - 4.7.0
- More info: https://documentation.wazuh.com/current/release-notes/release-4-7-0.html
* Tue Oct 31 2023 support <info@wazuh.com> - 4.6.0
- More info: https://documentation.wazuh.com/current/release-notes/release-4-6-0.html
* Tue Oct 24 2023 support <info@wazuh.com> - 4.5.4
- More info: https://documentation.wazuh.com/current/release-notes/release-4-5-4.html
* Tue Oct 10 2023 support <info@wazuh.com> - 4.5.3
- More info: https://documentation.wazuh.com/current/release-notes/release-4-5-3.html
* Thu Aug 31 2023 support <info@wazuh.com> - 4.5.2
- More info: https://documentation.wazuh.com/current/release-notes/release-4-5-2.html
* Thu Aug 24 2023 support <info@wazuh.com> - 4.5.1
- More info: https://documentation.wazuh.com/current/release-notes/release-4-5.1.html
* Thu Aug 10 2023 support <info@wazuh.com> - 4.5.0
- More info: https://documentation.wazuh.com/current/release-notes/release-4-5-0.html
* Mon Jul 10 2023 support <info@wazuh.com> - 4.4.5
- More info: https://documentation.wazuh.com/current/release-notes/release-4-4-5.html
* Tue Jun 13 2023 support <info@wazuh.com> - 4.4.4
- More info: https://documentation.wazuh.com/current/release-notes/release-4-4-4.html
* Thu May 25 2023 support <info@wazuh.com> - 4.4.3
- More info: https://documentation.wazuh.com/current/release-notes/release-4-4-3.html
* Mon May 08 2023 support <info@wazuh.com> - 4.4.2
- More info: https://documentation.wazuh.com/current/release-notes/release-4-4-2.html
* Mon Apr 17 2023 support <info@wazuh.com> - 4.4.1
- More info: https://documentation.wazuh.com/current/release-notes/release-4-4-1.html
* Wed Jan 18 2023 support <info@wazuh.com> - 4.4.0
- More info: https://documentation.wazuh.com/current/release-notes/release-4-4-0.html
* Thu Nov 10 2022 support <info@wazuh.com> - 4.3.10
- More info: https://documentation.wazuh.com/current/release-notes/release-4-3-10.html
* Mon Oct 03 2022 support <info@wazuh.com> - 4.3.9
- More info: https://documentation.wazuh.com/current/release-notes/release-4-3-9.html
* Mon Sep 19 2022 support <info@wazuh.com> - 4.3.8
- More info: https://documentation.wazuh.com/current/release-notes/release-4-3-8.html
* Mon Aug 08 2022 support <info@wazuh.com> - 4.3.7
- More info: https://documentation.wazuh.com/current/release-notes/release-4-3-7.html
* Thu Jul 07 2022 support <info@wazuh.com> - 4.3.6
- More info: https://documentation.wazuh.com/current/release-notes/release-4-3-6.html
* Wed Jun 29 2022 support <info@wazuh.com> - 4.3.5
- More info: https://documentation.wazuh.com/current/release-notes/release-4-3-5.html
* Tue Jun 07 2022 support <info@wazuh.com> - 4.3.4
- More info: https://documentation.wazuh.com/current/release-notes/release-4-3-4.html
* Tue May 31 2022 support <info@wazuh.com> - 4.3.3
- More info: https://documentation.wazuh.com/current/release-notes/release-4-3-3.html
* Mon May 30 2022 support <info@wazuh.com> - 4.3.2
- More info: https://documentation.wazuh.com/current/release-notes/release-4-3-2.html
* Wed May 18 2022 support <info@wazuh.com> - 4.3.1
- More info: https://documentation.wazuh.com/current/release-notes/release-4-3-1.html
* Thu May 05 2022 support <info@wazuh.com> - 4.3.0
- More info: https://documentation.wazuh.com/current/release-notes/release-4-3-0.html
